version: '3.5'

services:
  bwv_db:
    networks:
      - looplijsten_backend
    build: ./bwv_db
    ports:
      - "5410:5432"
    environment:
      POSTGRES_DB: looplijsten_bwv
      POSTGRES_USER: looplijsten_bwv
      POSTGRES_PASSWORD: insecure
  database:
    networks:
      - looplijsten_backend
    image: amsterdam/postgres11
    shm_size: '512m'
    ports:
      - "5409:5432"
    environment:
      POSTGRES_DB: looplijsten
      POSTGRES_USER: looplijsten
      POSTGRES_PASSWORD: insecure
  api:
    networks:
        - looplijsten_backend
    build:
      context: ./app
      args:
        - "INTEGRALE_AANPAK_ONDERMIJNING_CREDS=${INTEGRALE_AANPAK_ONDERMIJNING_CREDS}"
        - "INTEGRALE_AANPAK_ONDERMIJNING_PERSONAL_ACCESS_TOKEN=${INTEGRALE_AANPAK_ONDERMIJNING_PERSONAL_ACCESS_TOKEN}"
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=settings.settings
      - DJANGO_SECRET_KEY=local
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=0.0.0.0,localhost
      - CORS_ORIGIN_WHITELIST=http://0.0.0.0:3000,http://localhost:3000
      - DATABASE_NAME=looplijsten
      - DATABASE_USER=looplijsten
      - DATABASE_PASSWORD=insecure
      - BWV_DB_NAME=looplijsten_bwv
      - BWV_DB_USER=looplijsten_bwv
      - BWV_DB_PASSWORD=insecure
      - SENTRY_DSN=https://foo@foo.data.amsterdam.nl/0
      - LOCAL_DEVELOPMENT_AUTHENTICATION=True
      - ZAKEN_API_URL=http://zaak-gateway:8000/api/v1
      - PUSH_ZAKEN=False # Disabled for local development, enable to test Zaken connection
      - UWSGI_HTTP=0.0.0.0:8000
      - SECRET_KEY_TOP_ZAKEN=SECRET_KEY_TOP_ZAKEN
    volumes:
      - ./app:/app
      - ./api/deploy:/deploy
    command: bash -c "/app/deploy/entrypoint.development.sh"
    depends_on:
      - database
      - bwv_db

networks:
  looplijsten_backend:
    driver: bridge
