services:
  api:
    hostname: api
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-salmagundi/top-backend}:${VERSION:-latest}
    build:
      context: ./app
    ports:
      - "8000:8000"
    command: bash -c "/app/wait-for.sh database:5432 && /app/deploy/entrypoint.development.sh"
