# Generated by Django 3.2.13 on 2024-07-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accesslogs", "0004_logentry_request_method"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LogEntry",
        ),
    ]
