# Generated by Django 3.2 on 2021-07-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0031_auto_20210427_1637"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamsettings",
            name="fraudprediction_pilot_enabled",
            field=models.BooleanField(
                default=False,
                help_text="enables fraudprediction A/B testing for this theme on AZA cases",
            ),
        ),
    ]
