# Generated by Django 3.2.13 on 2022-07-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0036_auto_20220525_2025"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamsettings",
            name="use_zaken_backend",
        ),
    ]
