# Generated by Django 3.2.13 on 2022-07-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0037_remove_teamsettings_use_zaken_backend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamsettings",
            name="zaken_team_name",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
