# Generated by Django 3.2.13 on 2022-07-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0038_alter_teamsettings_zaken_team_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teamsettings",
            old_name="zaken_team_name",
            new_name="zaken_team_id",
        ),
    ]
