# Generated by Django 3.2.13 on 2022-07-11 08:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0039_rename_zaken_team_name_teamsettings_zaken_team_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="daysettings",
            name="districts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
