# Generated by Django 5.2.8 on 2026-03-17 10:40

import apps.planner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0043_remove_daysettings_week_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weights",
            name="fraud_probability",
        ),
        migrations.AlterField(
            model_name="daysettings",
            name="postal_code_ranges",
            field=models.JSONField(
                blank=True,
                default=apps.planner.models.day_settings__postal_code_ranges__default,
            ),
        ),
    ]
