# Generated by Django 5.2.12 on 2026-04-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0044_remove_weights_fraud_probability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daysettings",
            name="housing_corporation_combiteam",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
