# Generated by Django 5.2.12 on 2026-10-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0046_teamsettings_manage_settings_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="daysettings",
            name="is_bed_and_breakfast",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
