# Generated by Django 3.2 on 2022-03-14 13:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0064_alter_itinerarysettings_start_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerarysettings",
            name="housing_corporations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="itinerarysettings",
            name="project_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
