# Generated by Django 3.2.13 on 2022-04-25 13:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0035_daysettings_housing_corporation_combiteam"),
        ("itinerary", "0066_itinerarysettings_housing_corporation_combiteam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itinerarysettings",
            name="day_settings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itinerary_day_settings",
                to="planner.daysettings",
            ),
        ),
        migrations.AlterField(
            model_name="postalcodesettings",
            name="range_end",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(1384),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="postalcodesettings",
            name="range_start",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(1384),
                ]
            ),
        ),
    ]
