# Generated by Django 3.2.13 on 2022-05-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0067_auto_20220425_1512"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itinerarysettings",
            name="exclude_stadia",
        ),
        migrations.RemoveField(
            model_name="itinerarysettings",
            name="primary_stadium",
        ),
        migrations.RemoveField(
            model_name="itinerarysettings",
            name="projects",
        ),
        migrations.RemoveField(
            model_name="itinerarysettings",
            name="secondary_stadia",
        ),
        migrations.RemoveField(
            model_name="itinerarysettings",
            name="sia_presedence",
        ),
    ]
