# Generated by Django 3.2.13 on 2022-07-11 08:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0068_auto_20220525_2025"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerarysettings",
            name="districts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
