# Generated by Django 5.2.8 on 2026-03-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0070_add_subjects_tags_daysetting_itinerary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itinerary",
            options={"verbose_name_plural": "Itineraries"},
        ),
    ]
