# Generated by Django 5.2.12 on 2026-04-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0071_alter_itinerary_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itinerarysettings",
            name="housing_corporation_combiteam",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
