# Generated by Django 5.2.12 on 2026-10-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0072_alter_itinerarysettings_housing_corporation_combiteam"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerarysettings",
            name="is_bed_and_breakfast",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
