image:
  registry: 127.0.0.1:5001
  imagePullPolicy: Always

host: top-b.local

secrets:
  certificate:
    enabled: false

network:
  allow-ingress:
    enabled: false

configMaps:
  env-vars:
    data:
      DJANGO_SETTINGS_MODULE: settings.settings
      DJANGO_SECRET_KEY: local
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: 0.0.0.0,localhost,api,top-backend.localhost,top-b.local
      CORS_ORIGIN_WHITELIST: http://0.0.0.0:3000,http://localhost:3000,http://0.0.0.0:2999,http://localhost:2999
      DATABASE_NAME: looplijsten
      DATABASE_USER: salmagundi
      DATABASE_PASSWORD: insecure
      DATABASE_HOST: psql-postgresql
      SENTRY_DSN: https://foo@foo.data.amsterdam.nl/0
      LOCAL_DEVELOPMENT_AUTHENTICATION: "True"
      LOCAL_DEVELOPMENT_USE_MULTIPROCESSING: "True"
      ZAKEN_API_URL: http://zaken-backend-wonen:8080/api/v1
      ZAKEN_API_HEALTH_URL: http:///zaken-backend-wonen:8080/health
      PUSH_ZAKEN: "True"
      UWSGI_HTTP: 0.0.0.0:8000
      SECRET_KEY_TOP_ZAKEN: SECRET_KEY_TOP_ZAKEN
      REDIS: default:insecure@redis-master:6379
deployments:
  top-backend:
    configMaps:
      - env-vars

  top-celery-worker:
    configMaps:
      - env-vars

  top-celery-beat:
    configMaps:
      - env-vars
 
services:
  top-backend:
    selector:
      component: top-backend
    ports:
      - port: 8080
        targetPort: 8000

ingress:
  top-backend-internal:
    className: nginx

jobs:
  certificate-init:
    enabled: false
