# Generated by Django 3.2.13 on 2022-05-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0036_auto_20220525_2025"),
        ("itinerary", "0068_auto_20220525_2025"),
        ("cases", "0019_auto_20210318_1028"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.RemoveField(
            model_name="stadiumlabel",
            name="stadium",
        ),
        migrations.DeleteModel(
            name="Stadium",
        ),
        migrations.DeleteModel(
            name="StadiumLabel",
        ),
    ]
