name: 'Install, lint, test & build'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Linting
      run: bash cleanup.sh
    - name: Create Docker Looplijsten Backend network
      run: docker network create top_network
    - name: Create Docker Top and Zaak Backend Bridge network
      run: docker network create top_and_zaak_backend_bridge
    - name: Build Docker image
      run: docker compose -f docker-compose.local.yml up -d
    - name: Run Tests
      run: docker compose -f docker-compose.local.yml exec -T api python manage.py test


      ###################################################
      # On failure
      ###################################################
    - if: ${{ failure() }}
      name: "ON FAILURE: Which containers were running while failing?"
      run: docker ps -a

    - if: ${{ failure() }}
      name: "ON FAILURE: Backend logs"
      run: docker logs top-backend-api-1
